language: generic
sudo: required
services:
    - docker

before_install:
  - docker build -t holhar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true holhar/docker-react npm run test
